use crate::prelude::*;
use super::wayland_client_core::*;

pub type wl_data_device_error = c_int;
pub type wl_data_device_manager_dnd_action = c_int;
pub type wl_data_offer_error = c_int;
pub type wl_data_source_error = c_int;
pub type wl_display_error = c_int;
pub type wl_keyboard_key_state = c_int;
pub type wl_keyboard_keymap_format = c_int;
pub type wl_output_mode = c_int;
pub type wl_output_subpixel = c_int;
pub type wl_output_transform = c_int;
pub type wl_pointer_axis = c_int;
pub type wl_pointer_axis_relative_direction = c_int;
pub type wl_pointer_axis_source = c_int;
pub type wl_pointer_button_state = c_int;
pub type wl_pointer_error = c_int;
pub type wl_seat_capability = c_int;
pub type wl_seat_error = c_int;
pub type wl_shell_error = c_int;
pub type wl_shell_surface_fullscreen_method = c_int;
pub type wl_shell_surface_resize = c_int;
pub type wl_shell_surface_transient = c_int;
pub type wl_shm_error = c_int;
pub type wl_shm_format = c_int;
pub type wl_subcompositor_error = c_int;
pub type wl_subsurface_error = c_int;
pub type wl_surface_error = c_int;

unsafe extern "C" {
    pub static wl_buffer_interface: wl_interface;
    pub static wl_callback_interface: wl_interface;
    pub static wl_compositor_interface: wl_interface;
    pub static wl_data_device_interface: wl_interface;
    pub static wl_data_device_manager_interface: wl_interface;
    pub static wl_data_offer_interface: wl_interface;
    pub static wl_data_source_interface: wl_interface;
    pub static wl_display_interface: wl_interface;
    pub static wl_fixes_interface: wl_interface;
    pub static wl_keyboard_interface: wl_interface;
    pub static wl_output_interface: wl_interface;
    pub static wl_pointer_interface: wl_interface;
    pub static wl_region_interface: wl_interface;
    pub static wl_registry_interface: wl_interface;
    pub static wl_seat_interface: wl_interface;
    pub static wl_shell_interface: wl_interface;
    pub static wl_shell_surface_interface: wl_interface;
    pub static wl_shm_interface: wl_interface;
    pub static wl_shm_pool_interface: wl_interface;
    pub static wl_subcompositor_interface: wl_interface;
    pub static wl_subsurface_interface: wl_interface;
    pub static wl_surface_interface: wl_interface;
    pub static wl_touch_interface: wl_interface;
}
